- hosts: vpn-host
  become: yes
  gather_facts: no
  roles:
    - role: ansible_prereq

    - role: lxd_host
      create_lxdbr0: yes

    - role: lxd_install_image
      name: "vpn-base-container"

    - vpn_host
