- hosts: localhost
  roles:
    - role: lxd_create_container
      name: "vpn-base-container"

- hosts: vpn-base-container
  gather_facts: no
  roles:
    - ansible_prereq
    - vpn_base_container

- hosts: localhost
  roles:
    - role: lxd_publish_image
      name: "vpn-base-container"
